services:
  java-db:
    image: 'postgres:latest'
    container_name: java-postgres-main
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - shared-network

  redis_cache:
    image: 'redis:latest'
    container_name: redis_cache
    ports:
      - '6379:6379'
    networks:
      - shared-network

  java-app:
    build: .
    container_name: java-spring-app
    user: root
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java-db:5432/mydatabase
      - PYTHON_SERVICE_URL=http://python-fastapi-service:8000
      - REDIS_HOST=redis_cache
    depends_on:
      - java-db
      - redis_cache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - temp_code_storage:/codes:rw
        # Пробрасываем статику (CSS/JS/Картинки)
      - ./src/main/resources/static:/app/src/main/resources/static
      # Пробрасываем шаблоны (HTML/Thymeleaf)
      - ./src/main/resources/templates:/app/src/main/resources/templates
    networks:
      - shared-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - shared-network
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: ai-career-network

volumes:
  # Теперь этот том зарегистрирован и Docker его увидит
  grafana-storage:
  temp_code_storage:
    name: my_global_code_storage
    driver: local