spring.application.name=AI Career Nav

# ??????
server.port=8080

# ???? ?????? (PostgreSQL ????? Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# GigaChat (????????)
gigachat.auth-key=DUMMY_KEY_FOR_TESTING
gigachat.max-tokens=12000
gigachat.temperature=0.3
gigachat.top-p=0.9
gigachat.repetition-penalty=1.05
gigachat.read-timeout-ms=30000
gigachat.verify-ssl-certs=false

# ???????????
logging.level.org.example.aicareernav1=DEBUG
logging.level.org.hibernate.SQL=DEBUG