spring.application.name=AI Career Nav
spring.datasource.hikari.connection-init-sql=CREATE SCHEMA IF NOT EXISTS aicareer

server.port=8086

# Устанавливаем уровень логирования для твоего пакета
logging.level.org.example.aicareernav1=DEBUG


# Формат логов (чтобы точно видеть, откуда пришло сообщение)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} : %msg%n

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=aicareer
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Имя хоста должно совпадать с именем сервиса в docker-compose.yml
spring.data.redis.host=redis
spring.data.redis.port=6379

spring.web.resources.chain.cache=false
spring.thymeleaf.cache=false

python.service.url=${PYTHON_URL:http://127.0.0.1:8000}

gigachat.auth-key=MDE5YTQwOGYtMmUwOS03MDQ5LThjNzUtYTk1OTgzZjljNzE2OmRkNWYxZGU3LWJjN2QtNDFjOS04MzE0LTRmYjNkYWYyZWQ0ZA==
gigachat.read-timeout-ms=30000
gigachat.verify-ssl-certs=false
gigachat.max-tokens=5000
gigachat.temperature=0.3
gigachat.top-p=0.9
gigachat.repetition-penalty=1.05

# JSP ViewResolver
spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp

# JSP support
spring.mvc.servlet.load-on-startup=1
logging.level.io.netty.resolver.dns=OFF
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.stdout.encoding=UTF-8

#Yandex GPT
yandex.gpt.api-key=AQVN3O1426jj2899X12CrIp4WPX38Xir12KYQhbx
yandex.gpt.folder-id=b1gpn42jbprht4pq6h3h
yandex.gpt.url=https://llm.api.cloud.yandex.net/foundationModels/v1/completion
yandex.gpt.max-tokens=2000
yandex.gpt.temperature=0.3
hh.oauth.client-id=I6O8J1J25EVGHMUSJQPF0T5K5MGS24N3EHBJN3MS8J9UBG6LNNQ1A18QO0OME2U1
hh.oauth.client-secret=M0GTKOQTDIRA2KBUMQICQP343QAHFKN56Q1CU9SQFPONN0NROIHUCIPGUVP2U144
hh.oauth.token-uri=https://hh.ru/oauth/token